#!/bin/sh
# Vendors stanli (github.com/seantalts/stanli), following this package's
# convention for bundled libraries
set -e

STANLI_REF="73a3c44a08881197353b4c40a894a17666d86d73"
STANLI_TARBALL="stanli-$STANLI_REF.tar.gz"
STANLI_URL="https://github.com/seantalts/stanli/archive/$STANLI_REF.tar.gz"

if [ ! -f "$STANLI_TARBALL" ]; then
  curl -sSL -o "$STANLI_TARBALL" "$STANLI_URL"
fi
tar -xf "$STANLI_TARBALL"
# Read the archive's single top-level directory rather than globbing the
# working tree: old upgrade snapshots are intentionally left here and would
# otherwise make STANLI_DIR contain multiple paths.
STANLI_DIR=$(tar -tf "$STANLI_TARBALL" | awk -F/ 'NF { print $1; exit }')
test -n "$STANLI_DIR" && test -d "$STANLI_DIR"

SRC=../src/stanli

rm -rf "$SRC"
# The PCH only depends on its umbrella header, not the vendored headers it
# includes.  Invalidate it so the next package build cannot reuse the prior
# stanli revision's cache.
rm -f ../src/include/stanli_pch.hpp.gch ../src/include/stanli_pch.hpp.pch
mkdir -p "$SRC/runtime"

cp -f "$STANLI_DIR/LICENSE" "$SRC/"

cp -Rf "$STANLI_DIR/runtime/include" "$SRC/runtime/"
cp -Rf "$STANLI_DIR/runtime/src" "$SRC/runtime/"
cp -Rf "$STANLI_DIR/runtime/kernels" "$SRC/runtime/"
rm -f "$SRC/runtime/include/stanli/README.md"

rm -f "$SRC/runtime/src/capi.cpp" \
      "$SRC/runtime/src/bridgestan_abi.cpp" \
      "$SRC/runtime/src/stanc_embed_c.cpp" \
      "$SRC/runtime/src/nuts.cpp" \
      "$SRC/runtime/src/estimate.cpp" \
      "$SRC/runtime/src/diagnose.cpp" \
      "$SRC/runtime/src/walnuts.cpp" \
      "$SRC/runtime/src/pathfinder.cpp" \
      "$SRC/runtime/src/data.cpp" \
      "$SRC/runtime/src/README.md" \
      "$SRC/runtime/src/OPTIMIZATIONS.md"
# Private helper for nuts.cpp/estimate.cpp/pathfinder.cpp only -- dead once
# all three algorithm frontends above are stripped.
rm -f "$SRC/runtime/src/initialize.hpp"
rm -f "$SRC/runtime/include/stanli/capi.h" \
      "$SRC/runtime/include/stanli/bridgestan_internal.hpp" \
      "$SRC/runtime/include/stanli/nuts.hpp" \
      "$SRC/runtime/include/stanli/estimate.hpp" \
      "$SRC/runtime/include/stanli/diagnose.hpp" \
      "$SRC/runtime/include/stanli/walnuts.hpp" \
      "$SRC/runtime/include/stanli/model_adapter.hpp"

python3 - "$SRC/runtime/include/stanli/optable.hpp" "$SRC/runtime/kernels" << 'EOF'
import glob
import os
import re
import sys

optable_path, kernels_dir = sys.argv[1], sys.argv[2]
text = open(optable_path).read()

def macro_body(name):
    # Everything after "#define NAME(X)" up to (and including) the first
    # line whose newline isn't escaped by a line-continuation backslash.
    m = re.search(r'#define\s+' + re.escape(name) + r'\(X\)(.*?)(?<!\\)\n',
                  text, re.S)
    assert m, f"{name}(X) not found -- optable.hpp changed upstream"
    return m.group(1)

# Discover the list's membership from STANLI_SCALAR_DENSITY_LIST(X)
# itself rather than naming its sub-lists, so a future reshuffle of the
# grouping upstream doesn't silently drop or duplicate a distribution.
sub_lists = re.findall(r'(STANLI_SCALAR_DENSITY_LIST_\w+)\(X\)',
                        macro_body("STANLI_SCALAR_DENSITY_LIST"))
assert sub_lists, ("no sub-lists in STANLI_SCALAR_DENSITY_LIST(X) -- "
                    "optable.hpp changed upstream")

entry_re = re.compile(
    r'X\(\s*([A-Z0-9_]+)\s*,\s*([a-z0-9_]+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)')
entries = []  # (code, fn, nargs, tier)
for sub in sub_lists:
    found = entry_re.findall(macro_body(sub))
    assert found, f"{sub}(X) has no entries -- optable.hpp changed upstream"
    entries.extend(found)

names = [fn for _, fn, _, _ in entries]
assert len(names) == len(set(names)), "a density name appears in two sub-lists"

# The files currently defining these entries are whatever kernels/*.cpp
# instantiate a density sub-list -- not a fixed filename list, since
# upstream is free to rename or regroup its shards.
shard_call_re = re.compile(
    r'STANLI_SCALAR_DENSITY_LIST_\w+\(STANLI_DEFINE_DENSITY_FWD\)')
old_shards = [p for p in glob.glob(os.path.join(kernels_dir, "*.cpp"))
              if shard_call_re.search(open(p).read())]
assert old_shards, ("no existing density shard files found -- "
                     "kernels/ layout changed upstream")
for p in old_shards:
    os.remove(p)

template = """// Generated by tools/upgrade_stanli.sh: one LPDF, one translation unit.
// See upgrade_stanli.sh for why -- grouping entries, even just the
// costliest two, does not amortize stan-math's per-distribution
// instantiation cost away.
#include "densities_impl.hpp"

namespace stanli {{
namespace dens {{

STANLI_DEFINE_DENSITY_FWD({code}, {fn}, {nargs}, {tier})

}}  // namespace dens
}}  // namespace stanli
"""
for code, fn, nargs, tier in entries:
    out_path = os.path.join(kernels_dir, f"densities_{fn}.cpp")
    assert not os.path.exists(out_path), f"{out_path} already exists"
    open(out_path, "w").write(
        template.format(code=code, fn=fn, nargs=nargs, tier=tier))
EOF
